---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: nats-bench
  name: nats-bench
spec:
  completions: 2
  parallelism: 2
  template:
    metadata:
      labels:
        app: nats-bench
    spec:
      restartPolicy: Never
      containers:
        - name: nats-bench
          image: 4lie/nats-bench
          imagePullPolicy: Always
          args:
            - -ns
            - "1"
            - -np
            - "1"
            - -s
            - nats://nats:4222
            - -n
            - "100"
            - hello
